#CONSULTAS DE AGRUPAMIENTO

SELECT COUNT(titulo) AS 'NUMERO DE ENTRADAS',categoria_id FROM entradas GROUP BY categoria_id

#CONSULTAS DE AGRUPAMIENTO CON CONDICIONES

SELECT COUNT(titulo) AS 'NUMERO DE ENTRADAS',categoria_id 
FROM entradas GROUP BY categoria_id HAVING COUNT(titulo) >= 2

/*
AVG	SACAR MEDIA O PROMEDIO
COUNT	CONTAR EL NÚMERO DE ELEMENTOS
MAX	VALOR MÁX DEL GRUPO
MIN	VALOR MÍN DEL GRUPO
SUM	SUMAR TODO EL CONTENIDO DEL GRUPO
*/

SELECT AVG(id) AS 'Medio de entradas' FROM entradas;
SELECT * FROM entradas;

SELECT MAX(id) AS 'MÁXIMO ID', titulo FROM entradas;

SELECT MIN(id) AS 'MÁXIMO ID', titulo FROM entradas;

SELECT SUM(id) AS 'MÁXIMO ID', titulo FROM entradas;
