CREATE TABLE usuarios(
  id INT(11) AUTO_INCREMENT NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  apellidos VARCHAR(255) DEFAULT 'hola que tal',
  email VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(255),
  CONSTRAINT pk_usuarios PRIMARY KEY(id)
);

#RENOMBRAR UNA TABLA
ALTER TABLE usuarios RENAME TO usuarios_renom;

#CAMBIAR NOMBRE DE UNA COLUMNA
ALTER TABLE usuarios_renom CHANGE apellidos apellido VARCHAR(100) NULL;

#MODIFICAR COLUMNA SIN CAMBIAR NOMBRE
ALTER TABLE usuarios_renom MODIFY apellido CHAR(40) NOT NULL;

#AÑADIR COLUMNA
ALTER TABLE usuarios_renom ADD website VARCHAR(100) NULL;

#AÑADIR RESTRICCIÓN A COLUMNA
ALTER TABLE usuarios_renom ADD CONSTRAINT uq_email UNIQUE(email);

#BORRAR UNA COLUMNA
ALTER TABLE usuarios_renom DROP website;